# Generated by Django 6.0.4 on 2026-04-18 18:21

import django.db.models.deletion
import reclamations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=300)),
                ('categorie', models.CharField(choices=[('retard', 'Retard de traitement'), ('erreur_doc', 'Erreur dans le document'), ('mauvais_service', 'Mauvais service'), ('paiement', 'Problème de paiement'), ('autre', 'Autre')], max_length=30)),
                ('description', models.TextField()),
                ('numero_ticket', models.CharField(default=reclamations.models.generate_ticket, max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours de traitement'), ('resolue', 'Résolue'), ('fermee', 'Fermée')], default='ouverte', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='reclamations/')),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='accounts.citoyen')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='messages/')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reclamations.reclamation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['date_envoi'],
            },
        ),
    ]
