# Generated by Django 6.0.4 on 2026-04-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('etat_civil', 'État Civil'), ('identite', "Documents d'identité"), ('transport', 'Transports'), ('autre', 'Autre')], max_length=50)),
                ('tarif', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delai_jours', models.IntegerField(default=5, verbose_name='Délai (jours)')),
                ('conditions', models.TextField(blank=True, verbose_name="Conditions d'accès")),
                ('documents_requis', models.TextField(blank=True, verbose_name='Documents requis')),
                ('actif', models.BooleanField(default=True)),
                ('icone', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Administratif',
                'verbose_name_plural': 'Services Administratifs',
                'ordering': ['categorie', 'nom'],
            },
        ),
    ]
