# Generated by Django 6.0.4 on 2026-04-18 18:21

import demandes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=demandes.models.generate_reference, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('en_attente_docs', 'En attente de documents'), ('en_traitement', 'En traitement'), ('traitee', 'Traitée'), ('rejetee', 'Rejetée'), ('livree', 'Livrée')], default='en_cours', max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('notes_citoyen', models.TextField(blank=True)),
                ('notes_agent', models.TextField(blank=True)),
                ('adresse_livraison', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_assignees', to='accounts.agentadministratif')),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='accounts.citoyen')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='services.serviceadministratif')),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_doc', models.CharField(choices=[('justificatif', 'Document justificatif'), ('officiel', 'Document officiel généré'), ('autre', 'Autre')], default='justificatif', max_length=30)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='demandes.demande')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
